### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/Kulture#1]
Migrated from: https://github.com/ligershark/Kulture/issues/41
Creator: jchannon 

I get this error on Sublime startup from time to time.

![screen shot 2014-10-31 at 15 58 12](https://cloud.githubusercontent.com/assets/105126/4863745/0a65fb54-6117-11e4-8372-c67b05cc432c.png)

**Comment by personalnadir** [comment]
I'm seeing this issue. However I don't have get the TypeError, which I assume was fixed. I get this error both on my home and work networks. Any ideas what might be causing it?

```Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/tap32/Library/Application Support/Sublime Text 3/Packages/Kulture/Completions.py", line 132, in run
    http_file = urllib.request.urlopen(request, timeout=self.timeout)
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 469, in open
  File "./python3.3/urllib/request.py", line 487, in _open
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 1289, in https_open
  File "./python3.3/urllib/request.py", line 1253, in do_open
  File "./python3.3/http/client.py", line 1147, in getresponse
  File "./python3.3/http/client.py", line 358, in begin
  File "./python3.3/http/client.py", line 320, in _read_status
  File "./python3.3/socket.py", line 297, in readinto
  File "./python3.3/ssl.py", line 493, in recv_into
  File "./python3.3/ssl.py", line 367, in read
socket.timeout: The read operation timed out

reloading plugin Kulture.Kulture

**Comment by personalnadir** [comment]
The timeout message is occurring because Completions.py requests https://www.myget.org/F/aspnetvnext/api/v2/Packages()?$select=Id&$format=json&orderby=DownloadCount&$top=100 and sets the request to timeout after 5 seconds. However on my computer connected by ethernet to my work network that URL takes around 33 seconds to resolve.
